version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Laravel app
      - "5173:5173" # Vite dev server
    volumes:
      - .:/var/www/html
      - ./node_modules:/var/www/html/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=
      - DB_CONNECTION=mysql
      - DB_HOST=103.127.135.176 # IP database server eksternal
      - DB_PORT=3306
      - DB_DATABASE=toko
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
